# Generated by Django 6.0.4 on 2026-04-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_profile_questionnaire_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="preferred_party",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
