# Generated by Django 6.0.4 on 2026-04-25 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('idp', models.IntegerField(primary_key=True, serialize=False)),
                ('bill_number', models.CharField(max_length=50)),
                ('title', models.TextField(blank=True)),
                ('initiator_name', models.TextField(blank=True, null=True)),
                ('initiator_type', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('procedure', models.CharField(blank=True, max_length=100, null=True)),
                ('law_type', models.CharField(blank=True, max_length=100, null=True)),
                ('decision_chamber', models.CharField(blank=True, max_length=100, null=True)),
                ('registered_at', models.DateField(blank=True, null=True)),
                ('adopted_at', models.DateField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('doc_expunere_url', models.URLField(blank=True, max_length=500, null=True)),
                ('doc_forma_url', models.URLField(blank=True, max_length=500, null=True)),
                ('doc_aviz_ces_url', models.URLField(blank=True, max_length=500, null=True)),
                ('doc_aviz_cl_url', models.URLField(blank=True, max_length=500, null=True)),
                ('doc_adoptata_url', models.URLField(blank=True, max_length=500, null=True)),
                ('ocr_expunere', models.TextField(blank=True, null=True)),
                ('ocr_aviz_ces', models.TextField(blank=True, null=True)),
                ('ocr_aviz_cl', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
                'db_table': 'bills',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VoteSession',
            fields=[
                ('idv', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('present', models.IntegerField(default=0)),
                ('for_votes', models.IntegerField(default=0)),
                ('against', models.IntegerField(default=0)),
                ('abstain', models.IntegerField(default=0)),
                ('absent', models.IntegerField(default=0)),
                ('by_party', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Vote Session',
                'verbose_name_plural': 'Vote Sessions',
                'db_table': 'vote_sessions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('bill', models.OneToOneField(db_column='bill_idp', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ai_analysis', serialize=False, to='bills.bill')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('title_short', models.CharField(blank=True, max_length=255, null=True)),
                ('key_ideas', models.JSONField(default=list)),
                ('impact_categories', models.JSONField(default=list)),
                ('affected_profiles', models.JSONField(default=list)),
                ('arguments', models.JSONField(default=dict)),
                ('pro_arguments', models.JSONField(default=list)),
                ('con_arguments', models.JSONField(default=list)),
                ('controversy_score', models.FloatField(blank=True, null=True)),
                ('passed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('dominant_party', models.CharField(blank=True, max_length=100, null=True)),
                ('vote_date', models.DateField(blank=True, null=True)),
                ('ocr_quality', models.CharField(blank=True, max_length=50, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'AI Analysis',
                'verbose_name_plural': 'AI Analyses',
                'db_table': 'ai_analyses',
                'managed': False,
            },
        ),
    ]
