# Generated by Django 6.0.4 on 2026-04-25 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillEvent',
            fields=[
                ('event_key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('idv', models.IntegerField(blank=True, null=True)),
                ('bill_number', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(default='cdep', max_length=50)),
                ('chamber', models.CharField(default='deputies', max_length=50)),
                ('vote_date', models.DateField(blank=True, null=True)),
                ('summary', models.JSONField(default=dict)),
                ('detected_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Bill Event',
                'verbose_name_plural': 'Bill Events',
                'db_table': 'bill_events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BillFlag',
            fields=[
                ('event_key', models.OneToOneField(db_column='event_key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='flag', serialize=False, to='bills.billevent')),
                ('idv', models.IntegerField(blank=True, null=True)),
                ('bill_number', models.CharField(blank=True, max_length=50, null=True)),
                ('event_type', models.CharField(max_length=100)),
                ('importance', models.CharField(max_length=50)),
                ('flags', models.JSONField(default=list)),
                ('classified_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Bill Flag',
                'verbose_name_plural': 'Bill Flags',
                'db_table': 'bill_flags',
                'managed': False,
            },
        ),
    ]
