# Generated by Django 6.0.4 on 2026-05-18 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_billevent_billflag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aianalysis',
            options={'managed': True, 'verbose_name': 'AI Analysis', 'verbose_name_plural': 'AI Analyses'},
        ),
        migrations.AlterModelOptions(
            name='bill',
            options={'managed': True, 'verbose_name': 'Bill', 'verbose_name_plural': 'Bills'},
        ),
        migrations.AlterModelOptions(
            name='billevent',
            options={'managed': True, 'verbose_name': 'Bill Event', 'verbose_name_plural': 'Bill Events'},
        ),
        migrations.AlterModelOptions(
            name='billflag',
            options={'managed': True, 'verbose_name': 'Bill Flag', 'verbose_name_plural': 'Bill Flags'},
        ),
        migrations.AlterModelOptions(
            name='votesession',
            options={'managed': True, 'verbose_name': 'Vote Session', 'verbose_name_plural': 'Vote Sessions'},
        ),
    ]
