# Generated by Django 6.0.4 on 2026-05-19 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_alter_aianalysis_options_alter_bill_options_and_more'),
    ]

    operations = [
    ]
