# Generated by Django 6.0.4 on 2026-05-19 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_auto_20260519_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectedProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Affected Profile',
                'verbose_name_plural': 'Affected Profiles',
                'db_table': 'affected_profiles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ImpactCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Impact Category',
                'verbose_name_plural': 'Impact Categories',
                'db_table': 'impact_categories',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='billevent',
            name='bill',
            field=models.ForeignKey(blank=True, db_column='idp', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='bills.bill'),
        ),
        migrations.AddField(
            model_name='billflag',
            name='bill',
            field=models.ForeignKey(blank=True, db_column='idp', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='bills.bill'),
        ),
        migrations.AddField(
            model_name='votesession',
            name='bill',
            field=models.ForeignKey(blank=True, db_column='bill_idp', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote_sessions', to='bills.bill'),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='rel_affected_profiles',
            field=models.ManyToManyField(blank=True, related_name='analyses', to='bills.affectedprofile'),
        ),
        migrations.CreateModel(
            name='BillArgument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pro', 'Pro'), ('con', 'Con'), ('general', 'General')], max_length=20)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_arguments', to='bills.aianalysis')),
            ],
            options={
                'db_table': 'ai_arguments',
                'ordering': ['type', 'order'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='rel_impact_categories',
            field=models.ManyToManyField(blank=True, related_name='analyses', to='bills.impactcategory'),
        ),
        migrations.CreateModel(
            name='KeyIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_key_ideas', to='bills.aianalysis')),
            ],
            options={
                'db_table': 'ai_key_ideas',
                'ordering': ['order'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PartyVoteResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(max_length=100)),
                ('for_votes', models.IntegerField(default=0)),
                ('against', models.IntegerField(default=0)),
                ('abstain', models.IntegerField(default=0)),
                ('absent', models.IntegerField(default=0)),
                ('vote_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_party_results', to='bills.votesession')),
            ],
            options={
                'db_table': 'party_vote_results',
                'managed': True,
                'unique_together': {('vote_session', 'party')},
            },
        ),
    ]
