# Generated by Django 6.0.4 on 2026-05-19 18:15

from django.db import migrations
from django.utils.text import slugify

def migrate_data(apps, schema_editor):
    AIAnalysis = apps.get_model('bills', 'AIAnalysis')
    VoteSession = apps.get_model('bills', 'VoteSession')
    ImpactCategory = apps.get_model('bills', 'ImpactCategory')
    AffectedProfile = apps.get_model('bills', 'AffectedProfile')
    KeyIdea = apps.get_model('bills', 'KeyIdea')
    BillArgument = apps.get_model('bills', 'BillArgument')
    PartyVoteResult = apps.get_model('bills', 'PartyVoteResult')

    # 1. Migrate AIAnalysis JSON data
    for analysis in AIAnalysis.objects.all():
        # Impact Categories
        for cat_name in analysis.impact_categories:
            if not cat_name: continue
            cat, _ = ImpactCategory.objects.get_or_create(
                name=cat_name,
                defaults={'slug': slugify(cat_name) or 'unknown'}
            )
            analysis.rel_impact_categories.add(cat)
        
        # Affected Profiles
        for prof_name in analysis.affected_profiles:
            if not prof_name: continue
            prof, _ = AffectedProfile.objects.get_or_create(
                name=prof_name,
                defaults={'slug': slugify(prof_name) or 'unknown'}
            )
            analysis.rel_affected_profiles.add(prof)
            
        # Key Ideas
        for i, idea_text in enumerate(analysis.key_ideas):
            if not idea_text: continue
            KeyIdea.objects.create(analysis=analysis, text=idea_text, order=i)
            
        # Arguments (Pro/Con/General)
        for i, arg_text in enumerate(analysis.pro_arguments):
            if not arg_text: continue
            BillArgument.objects.create(analysis=analysis, type='pro', text=arg_text, order=i)
        for i, arg_text in enumerate(analysis.con_arguments):
            if not arg_text: continue
            BillArgument.objects.create(analysis=analysis, type='con', text=arg_text, order=i)
        
        # General arguments from the 'arguments' dict if any
        if isinstance(analysis.arguments, dict):
            for i, (key, value) in enumerate(analysis.arguments.items()):
                if not value: continue
                text = f"{key}: {value}" if key not in ('pro', 'con') else str(value)
                BillArgument.objects.create(analysis=analysis, type='general', text=text, order=i)

    # 2. Migrate VoteSession party results
    for session in VoteSession.objects.all():
        # session.by_party is a list of dicts like [{"party": "PSD", "for": 10, ...}]
        for party_data in session.by_party:
            if not isinstance(party_data, dict) or 'party' not in party_data:
                continue
            PartyVoteResult.objects.get_or_create(
                vote_session=session,
                party=party_data['party'],
                defaults={
                    'for_votes': party_data.get('for', 0),
                    'against': party_data.get('against', 0),
                    'abstain': party_data.get('abstain', 0),
                    'absent': party_data.get('absent', 0),
                }
            )

class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_rel_models_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_data, migrations.RunPython.noop),
    ]
