# Generated by Django 6.0.4 on 2026-05-19 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_migrate_json_to_relational'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aianalysis',
            name='affected_profiles',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='arguments',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='con_arguments',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='impact_categories',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='key_ideas',
        ),
        migrations.RemoveField(
            model_name='aianalysis',
            name='pro_arguments',
        ),
        migrations.RemoveField(
            model_name='votesession',
            name='by_party',
        ),
    ]
