# Generated by Django 6.0.4 on 2026-05-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_remove_legacy_json_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aianalysis',
            name='dominant_party',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aianalysis',
            name='vote_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bill',
            name='registered_at',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='billevent',
            name='vote_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='votesession',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
