/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MpsRouteImport } from './routes/mps'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as MpsIndexRouteImport } from './routes/mps/index'
import { Route as MpsSlugRouteImport } from './routes/mps/$slug'
import { Route as BillsIdRouteImport } from './routes/bills/$id'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminStatsRouteImport } from './routes/admin/stats'
import { Route as AdminBillsRouteImport } from './routes/admin/bills'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MpsRoute = MpsRouteImport.update({
  id: '/mps',
  path: '/mps',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const MpsIndexRoute = MpsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MpsRoute,
} as any)
const MpsSlugRoute = MpsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MpsRoute,
} as any)
const BillsIdRoute = BillsIdRouteImport.update({
  id: '/bills/$id',
  path: '/bills/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStatsRoute = AdminStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillsRoute = AdminBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/chat': typeof ChatRoute
  '/mps': typeof MpsRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/admin/bills': typeof AdminBillsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/bills/$id': typeof BillsIdRoute
  '/mps/$slug': typeof MpsSlugRoute
  '/mps/': typeof MpsIndexRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/chat': typeof ChatRoute
  '/onboarding': typeof OnboardingRoute
  '/admin/bills': typeof AdminBillsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/bills/$id': typeof BillsIdRoute
  '/mps/$slug': typeof MpsSlugRoute
  '/mps': typeof MpsIndexRoute
  '/profile': typeof ProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/chat': typeof ChatRoute
  '/mps': typeof MpsRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/admin/bills': typeof AdminBillsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/bills/$id': typeof BillsIdRoute
  '/mps/$slug': typeof MpsSlugRoute
  '/mps/': typeof MpsIndexRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/chat'
    | '/mps'
    | '/onboarding'
    | '/admin/bills'
    | '/admin/stats'
    | '/admin/users'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/register'
    | '/auth/reset-password'
    | '/bills/$id'
    | '/mps/$slug'
    | '/mps/'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/chat'
    | '/onboarding'
    | '/admin/bills'
    | '/admin/stats'
    | '/admin/users'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/register'
    | '/auth/reset-password'
    | '/bills/$id'
    | '/mps/$slug'
    | '/mps'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/chat'
    | '/mps'
    | '/onboarding'
    | '/admin/bills'
    | '/admin/stats'
    | '/admin/users'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/register'
    | '/auth/reset-password'
    | '/bills/$id'
    | '/mps/$slug'
    | '/mps/'
    | '/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ChatRoute: typeof ChatRoute
  MpsRoute: typeof MpsRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  BillsIdRoute: typeof BillsIdRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mps': {
      id: '/mps'
      path: '/mps'
      fullPath: '/mps'
      preLoaderRoute: typeof MpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mps/': {
      id: '/mps/'
      path: '/'
      fullPath: '/mps/'
      preLoaderRoute: typeof MpsIndexRouteImport
      parentRoute: typeof MpsRoute
    }
    '/mps/$slug': {
      id: '/mps/$slug'
      path: '/$slug'
      fullPath: '/mps/$slug'
      preLoaderRoute: typeof MpsSlugRouteImport
      parentRoute: typeof MpsRoute
    }
    '/bills/$id': {
      id: '/bills/$id'
      path: '/bills/$id'
      fullPath: '/bills/$id'
      preLoaderRoute: typeof BillsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stats': {
      id: '/admin/stats'
      path: '/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AdminStatsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bills': {
      id: '/admin/bills'
      path: '/bills'
      fullPath: '/admin/bills'
      preLoaderRoute: typeof AdminBillsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBillsRoute: typeof AdminBillsRoute
  AdminStatsRoute: typeof AdminStatsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBillsRoute: AdminBillsRoute,
  AdminStatsRoute: AdminStatsRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MpsRouteChildren {
  MpsSlugRoute: typeof MpsSlugRoute
  MpsIndexRoute: typeof MpsIndexRoute
}

const MpsRouteChildren: MpsRouteChildren = {
  MpsSlugRoute: MpsSlugRoute,
  MpsIndexRoute: MpsIndexRoute,
}

const MpsRouteWithChildren = MpsRoute._addFileChildren(MpsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ChatRoute: ChatRoute,
  MpsRoute: MpsRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  BillsIdRoute: BillsIdRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
