# Generated by Django 6.0.4 on 2026-04-25 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parliamentarian',
            fields=[
                ('mp_slug', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('mp_name', models.CharField(blank=True, max_length=255, null=True)),
                ('party', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Parliamentarian',
                'verbose_name_plural': 'Parliamentarians',
                'db_table': 'parliamentarians',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MPVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(blank=True, max_length=100, null=True)),
                ('vote', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'MP Vote',
                'verbose_name_plural': 'MP Votes',
                'db_table': 'mp_votes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImpactScore',
            fields=[
                ('parliamentarian', models.OneToOneField(db_column='mp_slug', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='impact_score', serialize=False, to='parliamentarians.parliamentarian')),
                ('score', models.FloatField(blank=True, null=True)),
                ('total_votes', models.IntegerField(default=0)),
                ('for_count', models.IntegerField(default=0)),
                ('against_count', models.IntegerField(default=0)),
                ('abstain_count', models.IntegerField(default=0)),
                ('absent_count', models.IntegerField(default=0)),
                ('categories_voted', models.JSONField(default=list)),
                ('narrative', models.TextField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Impact Score',
                'verbose_name_plural': 'Impact Scores',
                'db_table': 'impact_scores',
                'managed': False,
            },
        ),
    ]
