# Generated by Django 6.0.4 on 2026-05-18 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parliamentarians', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impactscore',
            options={'managed': True, 'verbose_name': 'Impact Score', 'verbose_name_plural': 'Impact Scores'},
        ),
        migrations.AlterModelOptions(
            name='mpvote',
            options={'managed': True, 'verbose_name': 'MP Vote', 'verbose_name_plural': 'MP Votes'},
        ),
        migrations.AlterModelOptions(
            name='parliamentarian',
            options={'managed': True, 'verbose_name': 'Parliamentarian', 'verbose_name_plural': 'Parliamentarians'},
        ),
    ]
