# Generated by Django 6.0.4 on 2026-05-19 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_rel_models_initial'),
        ('parliamentarians', '0002_alter_impactscore_options_alter_mpvote_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpvote',
            name='parliamentarian',
            field=models.ForeignKey(blank=True, db_column='mp_slug', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='parliamentarians.parliamentarian'),
        ),
        migrations.AddField(
            model_name='mpvote',
            name='vote_session',
            field=models.ForeignKey(blank=True, db_column='idv', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mp_votes', to='bills.votesession'),
        ),
        migrations.AddField(
            model_name='parliamentarian',
            name='chamber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='mpvote',
            unique_together={('vote_session', 'parliamentarian')},
        ),
    ]
