# Generated by Django 6.0.4 on 2026-05-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliamentarians', '0003_rel_models_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpvote',
            name='party',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mpvote',
            name='vote',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parliamentarian',
            name='chamber',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parliamentarian',
            name='county',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parliamentarian',
            name='mp_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parliamentarian',
            name='party',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
